version: "3.6"

services:
  wsdebug:
    image: quay.io/openware/ws-debug:0.0.3
    labels:
      - "traefik.http.routers.wsdebug.rule=Host(`www.app.local`)"
      - "traefik.http.routers.wsdebug.entrypoints=web"
      - "traefik.http.services.wsdebug.loadbalancer.server.port=8080"
      - "traefik.enable=true"

  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.app.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.enable=true"

  traefik:
    image: traefik:2.1.8
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
